server:
  port: 9999
  session:
    timeout: 60


spring:
    redis:
       host: 127.0.0.1
       port: 56379
       password:
       timeout: 0
       pool:
           max-active: 8
           max-wait: -1
           max-idle: 8
           min-idle: 0
    session:
      store-type: none

#server.enviroment: test