#dubbo
dubbo.application.id: xiao-dubbo
dubbo.application.name: server
## ProtocolConfig Bean
dubbo.protocol.id: dubbo
dubbo.protocol.name: dubbo
dubbo.protocol.port: 2889
## RegistryConfig Bean
dubbo.registry.protocol: zookeeper
dubbo.registry.address: 127.0.0.1:32181
dubbo.provider.version: 1.0.0.dev
dubbo.provider.group: xiao
dubbo.consumer.version: 1.0.0.dev
dubbo.consumer.group: xiao